services:
  streamlit-app:
    build:
      context: .
      dockerfile: Dockerfile.streamlit
    ports:
      - "8501:8501"
    environment:
      - GROQ_API_KEY=${GROQ_API_KEY}
      - API_KEY=${API_KEY}
      - MODEL_ID=${MODEL_ID}
      - MODEL_BASE_URL=${MODEL_BASE_URL}
    # env_file:
    #   - .env
    networks:
      - crewai-network

networks:
  crewai-network:
    driver: bridge